title: "Kankakee Community College"
site_name: Workforce Services
public-url: "https://www.kcc.edu"
theme: "kcc-gem-theme"
google-tag_key: Google Tag Manager key goes here
nav_links:
  - link_text: About
    link_href: 'about'
    button: false
  - link_text: Workshops & Events
    link_href: 'workshops-and-events'
    button: false
  - link_text: Career Training
    link_href: 'career-training'
    button: false
  - link_text: Resources
    link_href: 'resources'
    button: false
  - link_text: Contact
    link_href: '#contact'
    button: false
  - link_text: Get Started
    link_href: 'service-eligibility-questionnaire'
    button: true
collections:
  posts:
    output: false
    _hide_content: true
  contacts:
    output: false
  testimonials:
    output: false
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    title: ''
    permalink: /:categories/:title/
    baseurl: ../../../
    categories: news
permalink: pretty
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
# Delete this comment and place description on this line
baseurl: "" # the subpath of your site, e.g. /blog
# include:
#   - "_pages"
#   - "_posts"

# include future posts? (true or false)
future: true
# Build settings
markdown: kramdown

exclude:
  - "gulpfile.js"
  - "gulp-tasks/"
  - "node_modules"
  - "npm-debug.log"
  - "package.json"
  - "package-lock.json"
  - "README.md"
  - "Gemfile"
  - "Gemfile.lock"
  - "gulpconfig.yml"
  - "/docs/"
  - "yarn.lock"
  - "/assets/adobe/"
  - "webpack.config.js"
  - "install.sh"
  - "siteicon.png"

uploads_dir: # specifies the default uploads directory for CloudCannon
  - "uploads/"

_comments:
  layout: Do NOT modify layouts. It may break things.
  baseurl: Do NOT modify baseurl. It WILL break all page links.
  categories: "FOR CATEGORIES <br/>SPORTS-SPECIFIC: <br/>1.) First enter the sport's category from this list <br/>2.) followed by the \"news\" category. <br/>(e.g. mens-basketball news) <br/>GENERAL NEWS: <br/>1.) Enter \"news\" category first <br/>2.) followed by the \"general\" category. <br/>(e.g. news general)"
  sport_category: Sport for which news item pertains. Gets pulled into news rollup.
  news_thumb_image: Must be 16:9 ratio image. Preferably 200px wide.
  description: "Descriptions are seen by search engines like Google and displayed in search results"

_options: # The CloudCannon options key
  layout: # We don't want users changing these!!
    hidden: true
  baseurl: # We don't want users changing these!!
    hidden: true
